version: "3.9"

services:
  frontend:
    container_name: frontend
    image: snak1o/shop
    environment:
      HOST_API: localhost:80
  redis:
    container_name: shop_redis
    image: redis:7-alpine
    env_file:
      - ./backend.env
    volumes:
      - $HOME/redisdata:/data
    command: redis-server --save 20 1 --loglevel warning
  postgres:
    image: postgres
    env_file:
      ./pgsql.env
    volumes:
      - $HOME/pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: .
    container_name: backend
    image: shop_backend
    env_file:
      - ./backend.env
      - ./pgsql.env
    environment:
      WAIT_HOSTS: postgres:5432
    depends_on:
      - postgres
    volumes:
      - ${HOME}/files:/app/files
  nginx:
    build: "./nginx"
    container_name: nginx
    image: shop_nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ${HOME}/files:/var/files