http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

pgsql:
  dbname: shop
  sslmode: disable

redis:
  defaultDB: 0

auth:
  accessTokenTTL: 1h
  refreshTokenTTL: 720h #30 days
