basePath: /api/v1
definitions:
  v1.signUpInput:
    properties:
      email:
        maxLength: 255
        type: string
      password:
        maxLength: 64
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
host: localhost:8000
info:
  contact: {}
  description: API server
  title: FinlandShop API
  version: "0.1"
paths:
  /users/auth/sign-up:
    post:
      consumes:
      - application/json
      description: Users sign-up
      parameters:
      - description: sign-up input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.signUpInput'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Sign-up
      tags:
      - users-auth
swagger: "2.0"
